version: '3.7'

services:
    db_empleado:
        image: postgres:12.0-alpine
        container_name: db_empleado
        volumes: 
            - postgres_data_empleado:/var/lib/postgresql/data/
        ports: 
            - 5432:5432
        env_file: 
            - ./.env
    pgadmin_empleado:
        image: dpage/pgadmin4
        container_name: pgadmin_empleado
        environment: 
            - PGADMIN_DEFAULT_EMAIL=cynthiariquelme86@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=admin
        volumes:
            - pgadmin4:/var/lib/pgadmin
        ports: 
            - 8081:80
        logging:
            driver: none  
volumes: 
    postgres_data_empleado:
    pgadmin4: