# Generated by Django 3.2 on 2022-09-13 20:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_auto_20220913_1943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habilidades',
            options={'verbose_name': 'Habilidad', 'verbose_name_plural': 'Habilidades Empleados'},
        ),
        migrations.AddField(
            model_name='empleado',
            name='hoja_vida',
            field=ckeditor.fields.RichTextField(default='texto'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='empleado',
            unique_together=set(),
        ),
    ]
